ALTER TABLE configuracao ALTER COLUMN odd_limite SET DATA TYPE DOUBLE PRECISION;
ALTER TABLE configuracao ALTER COLUMN peso_media_pontos SET DATA TYPE DOUBLE PRECISION;
ALTER TABLE configuracao ALTER COLUMN peso_valorizacao SET DATA TYPE DOUBLE PRECISION;
ALTER TABLE configuracao ALTER COLUMN peso_desempenho SET DATA TYPE DOUBLE PRECISION;
ALTER TABLE configuracao ALTER COLUMN peso_fator_casa SET DATA TYPE DOUBLE PRECISION;
ALTER TABLE configuracao ALTER COLUMN peso_time_favorito SET DATA TYPE DOUBLE PRECISION;
